INSERT into etat(displayedString,modelEtats_id,valuesArray) values('',2,'{"choices":["Notification"],"dateField":{"displayedString":"Date", "type":"date", "value":null}}');
INSERT into etat(displayedString,modelEtats_id,valuesArray) values('',2,'{"choices":["Copie du Marché","Visé","Enregistré"]}');
INSERT into etat(displayedString,modelEtats_id,valuesArray) values('',2,'{"choices":["Ordre de Service"],"dateField":{"displayedString":"Date", "type":"date", "value":null}}');
INSERT into etat(displayedString,modelEtats_id,valuesArray) values('',2,'{"choices":["Bons de Commande Achat :"],"dateField":{"displayedString":"Date", "type":"date" ,"value":null}}');
INSERT into etat(displayedString,modelEtats_id,valuesArray) values('',2,'{"delay":{"displayedString":"Délai d’exécution","value":null,"type":"number","suffix":"jours"},"dateField":{"displayedString":"Date Fin d’exécution prévue ", "type":"date", "value":null}}');
INSERT into etat(displayedString,modelEtats_id,valuesArray) values('',2,'{"choices":["Caution Définitive"],"dateField":{"displayedString":"Date", "type":"date" ,"value":null},"quantity":{"displayedString":"Montant","type":"double" ,"value":null}}');
INSERT into etat(displayedString,modelEtats_id,valuesArray) values('',2,'{"choices":["Retour Caut.  Prov."] ,"dateField":{"displayedString":"Date", "type":"date" ,"value":null},"quantity":{"displayedString":"Montant","type":"double" ,"value":null}}');
INSERT into etat(displayedString,modelEtats_id,valuesArray) values('',2,'{"choices":["BL Fournisseurs :  "],"dateField":{"displayedString":"Date", "type":"date" ,"value":null}}');
INSERT into etat(displayedString,modelEtats_id,valuesArray) values('',2,'{"choices":["Bon de Livraison","Daté","Signé"]}');
INSERT into etat(displayedString,modelEtats_id,valuesArray) values('',2,'{"choices":["PV de RP"], "dateField":{"displayedString":"Date", "type":"date" ,"value":null}}');
INSERT into etat(displayedString,modelEtats_id,valuesArray) values('',2,'{"choices":["Caution R.G	"], "dateField":{"displayedString":"Date", "type":"date" ,"value":null},"quantity":{"displayedString":"Montant","type":"double" ,"value":null}}');
INSERT into etat(displayedString,modelEtats_id,valuesArray) values('',2,'{"choices":["Facture (Décompte) ","Signé"]}');
INSERT into etat(displayedString,modelEtats_id,valuesArray) values('',2,'{"dateField":{"displayedString":"Date", "type":"date" ,"value":null}, "quantity":{"displayedString":"N°","type":"number" ,"value":null}');
INSERT into etat(displayedString,modelEtats_id,valuesArray) values('soumission',1,'{"choices":["Oui ","Non"]}');
INSERT into etat(displayedString,modelEtats_id,valuesArray) values('si non Motif',1,'{"textfield":{"displayedString":"si non Motif", "type":"text" ,"value":null}}');
INSERT into etat(displayedString,modelEtats_id,valuesArray) values('avant vente',1,'{"choices":["Oui ","Non"]}');
INSERT into etat(displayedString,modelEtats_id,valuesArray) values('soumissionaires',1,'{"linkes":{"pointing":"entreprise","value":[]}}');
