INSERT into etat(displayedString,valuesArray) values('','{"choices":["Notification"],"dateField":{"displayedString":"Date", "type":"date", "value":null}}');
INSERT into etat(displayedString,valuesArray) values('','{"choices":["Copie du Marché","Visé","Enregistré"]}');
INSERT into etat(displayedString,valuesArray) values('','{"choices":["Ordre de Service"],"dateField":{"displayedString":"Date", "type":"date", "value":null}}');
INSERT into etat(displayedString,valuesArray) values('','{"choices":["Bons de Commande Achat :"],"dateField":{"displayedString":"Date", "type":"date" ,"value":null}}');
INSERT into etat(displayedString,valuesArray) values('','{"delay":{"displayedString":"Délai d’exécution","value":null,"type":"number","suffix":"jours"},"dateField":{"displayedString":"Date Fin d’exécution prévue ", "type":"date", "value":null}}');
INSERT into etat(displayedString,valuesArray) values('','{"choices":["Caution Définitive"],"dateField":{"displayedString":"Date", "type":"date" ,"value":null},"quantity":{"displayedString":"Montant","type":"double" ,"value":null}}');
INSERT into etat(displayedString,valuesArray) values('','{"choices":["Retour Caut.  Prov."] ,"dateField":{"displayedString":"Date", "type":"date" ,"value":null},"quantity":{"displayedString":"Montant","type":"double" ,"value":null}}');
INSERT into etat(displayedString,valuesArray) values('','{"choices":["BL Fournisseurs :  "],"dateField":{"displayedString":"Date", "type":"date" ,"value":null}}');
INSERT into etat(displayedString,valuesArray) values('','{"choices":["Bon de Livraison","Daté","Signé"]}');
INSERT into etat(displayedString,valuesArray) values('','{"choices":["PV de RP"], "dateField":{"displayedString":"Date", "type":"date" ,"value":null}}');
INSERT into etat(displayedString,valuesArray) values('','{"choices":["Caution R.G	"], "dateField":{"displayedString":"Date", "type":"date" ,"value":null},"quantity":{"displayedString":"Montant","type":"double" ,"value":null}}');
INSERT into etat(displayedString,valuesArray) values('','{"choices":["Facture (Décompte) ","Signé"]}');
INSERT into etat(displayedString,valuesArray) values('','{"dateField":{"displayedString":"Date", "type":"date" ,"value":null}, "quantity":{"displayedString":"N°","type":"number" ,"value":null}');
INSERT into etat(displayedString,valuesArray) values('','{"choices":["Oui ","Non"]}');
INSERT into etat(displayedString,valuesArray) values('','{"textfield":{"displayedString":"Motif", "type":"text" ,"value":null}}');
INSERT into etat(displayedString,valuesArray) values('','{"choices":["Oui ","Non"]}');
INSERT into etat(displayedString,valuesArray) values('','{"linkes":{"pointing":"entreprise","value":[]}}');
