appel:
    path:     /
    defaults: { _controller: "medaSysAOBundle:appel:index" }

appel_show:
    path:     /{id}/show
    defaults: { _controller: "medaSysAOBundle:appel:show" }

appel_new:
    path:     /new
    defaults: { _controller: "medaSysAOBundle:appel:new" }

appel_create:
    path:     /create
    defaults: { _controller: "medaSysAOBundle:appel:create" }
    methods:  POST

appel_edit:
    path:     /{id}/edit
    defaults: { _controller: "medaSysAOBundle:appel:edit" }

appel_update:
    path:     /{id}/update
    defaults: { _controller: "medaSysAOBundle:appel:update" }
    methods:  [POST, PUT]

cautionnement:
    path:     /{id}/cautionnement
    defaults: { _controller: "medaSysAOBundle:appel:cautionnement" }
    methods:  [POST, PUT,GET]
soumissionnaires:
    path:     /{id}/soumissionnaires
    defaults: { _controller: "medaSysAOBundle:appel:soumissionnaires" }
    methods:  [POST, PUT,GET]
qualificationTechnique:
    path:     /{id}/qualificationTechnique
    defaults: { _controller: "medaSysAOBundle:appel:qualificationTechnique" }
    methods:  [POST, PUT,GET]
installation:
    path:     /{id}/installation
    defaults: { _controller: "medaSysAOBundle:appel:installation" }
    methods:  [POST, PUT,GET]


appel_delete:
    path:     /{id}/delete
    defaults: { _controller: "medaSysAOBundle:appel:delete" }
    methods:  [POST, DELETE]


appel_ficheProjet:
    path:     /{id}/{reportName}/report
    defaults: { _controller: "medaSysAOBundle:appel:ficheProjet" }
    methods:  [POST, PUT,GET]
