lot:
    path:     /
    defaults: { _controller: "medaSysAOBundle:lot:index" }

lot_show:
    path:     /{id}/show
    defaults: { _controller: "medaSysAOBundle:lot:show" }

lot_new:
    path:     /new
    defaults: { _controller: "medaSysAOBundle:lot:new" }

lot_create:
    path:     /create
    defaults: { _controller: "medaSysAOBundle:lot:create" }
    requirements: { _method: post }

lot_edit:
    path:     /{id}/edit
    defaults: { _controller: "medaSysAOBundle:lot:edit" }

lot_update:
    path:     /{id}/update
    defaults: { _controller: "medaSysAOBundle:lot:update" }
    requirements: { _method: post|put }

lot_delete:
    path:     /{id}/delete
    defaults: { _controller: "medaSysAOBundle:lot:delete" }
    requirements: { _method: post|delete }
