situationappel:
    path:     /
    defaults: { _controller: "medaSysAOBundle:situationAppel:index" }

situationappel_show:
    path:     /{id}/show
    defaults: { _controller: "medaSysAOBundle:situationAppel:show" }

situationappel_new:
    path:     /new
    defaults: { _controller: "medaSysAOBundle:situationAppel:new" }

situationappel_create:
    path:     /create
    defaults: { _controller: "medaSysAOBundle:situationAppel:create" }
    methods:  POST

situationappel_edit:
    path:     /{id}/edit
    defaults: { _controller: "medaSysAOBundle:situationAppel:edit" }

situationappel_update:
    path:     /{id}/update
    defaults: { _controller: "medaSysAOBundle:situationAppel:update" }
    methods:  [POST, PUT]

situationappel_delete:
    path:     /{id}/delete
    defaults: { _controller: "medaSysAOBundle:situationAppel:delete" }
    methods:  [POST, DELETE]
